apiVersion: v2
kubeVersion: ">= 1.26.0"
name: portal-bedoccupancy
description: Helm Chart for the portal-bedoccupancy frontend application
type: application
version: 1.5.6
appVersion: "1.5.6"
icon: https://avatars.githubusercontent.com/u/55493511?s=200&v=4
